# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    cpus-per-task: 4
    mem: 16GB
    output: results/logs/slurm-%x.%A.%a.log
    gres: ""
    constraint: ""

Dorado_baseCalling_alignment:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 6
    mem: 32GB

dnascent_index:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 4

dnascent_detect:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 12
    mem: 16GB

dnascent_forksense:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 12
    mem: 16GB
