# UCSC genome address
nanopore_samples_sheet: "config/samples.csv"
label_order: "EdU,BrdU"
genome_address: "http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz"
#genome_address: "https://hgdownload.soe.ucsc.edu/goldenPath/danRer11/bigZips/danRer11.fa.gz"
basecalling_mode: "hac"
dorado_device: "cuda:all"
# Modules
minimap2: "minimap2/2.28"
dorado: "dorado/0.8.1"
cuda: "cuda/12"
samtools: "samtools/1.18"
dnascent: "dnascent/4.0.3"
pod5_directory: "/archive/sansamc/NanoporeSequencing/CS_20250428/20250428/20250428_1853_P2S-02862-A_PBA15434_3150224e/pod5"
#pod5_directory: "./data/"
chunks_per_bam: "2"
samtools_threads: "12"
minimum_read_length: 30000
detect_threads: "12"
forkSense_threads: "12"
